workflows:
  ios-release:
    name: iOS Release Workflow
    environment:
      vars:
        XCODE_WORKSPACE: "Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
      flutter: stable
    triggering:
      events:
        - push
    scripts:
      - name: Install dependencies
        script: |
          flutter pub get
      - name: Build iOS release
        script: |
          flutter build ipa \
            --release \
            --no-codesign \
            --export-options-plist=ios/Runner/export_options.plist
    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/xcarchive/**/*.dSYM
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        submit_to_app_store: false
