# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Dart

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
         flutter-version: 3.27.0
      - run: flutter pub get
      # - run: flutter test
      - run: flutter build apk --release
      # - run: flutter build appbundle
      - name: Move APK to apkBuild folder
        run: mv build/app/outputs/flutter-apk/app-release.apk ./apkBuild/

      - name: Move APK to apkBuild folder
        run: mv build/app/outputs/flutter-apk/app-release.apk ./apkBuild/

      - name: Commit APK
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add apkBuild/app-release.apk
          git commit -m "Automatically built and pushed apk to repository" -a

      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.sha }}
          draft: false
          prerelease: false
      - name: Upload APK to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./build/app/outputs/flutter-apk/app-release.apk
          asset_name: app-release.apk
          asset_content_type: application/vnd.android.package-archive
